"""Exports the FastAPI app's OpenAPI schema to openapi/openapi.yaml.

The schema is generated from the actual routes and Pydantic models in
app/api/routes.py and app/models/schemas.py - never hand-edit the YAML file
this writes, since it would just be overwritten (and drift from reality) the
next time this runs. Re-run this after adding/changing any endpoint or
request/response model:

    python -m scripts.export_openapi

Requires pyyaml (see requirements-dev.txt) in addition to the app's own
requirements.txt - it isn't needed to run the service itself, only to
regenerate this file.
"""
from pathlib import Path

import yaml

from app.main import app

OUTPUT_PATH = Path(__file__).resolve().parent.parent / "openapi" / "openapi.yaml"


def main() -> None:
    schema = app.openapi()
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with OUTPUT_PATH.open("w") as f:
        f.write("# Generated by scripts/export_openapi.py - do not hand-edit.\n")
        f.write("# Re-run that script after changing any endpoint or schema.\n")
        yaml.safe_dump(schema, f, sort_keys=False, default_flow_style=False, allow_unicode=True)
    print(f"Wrote {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
